apiVersion: apps/v1 
kind: Deployment
metadata:
  name: music-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
      - name: music-app
        image: us-central1-docker.pkg.dev/gen-lang-client-0729539659/llmops-repo/llmops-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: llmops-secrets
              key: GROQ_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: music-app-service
spec:
  selector:
    app: music-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer  